# Generated by Django 3.0.3 on 2020-03-14 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa kategotii')),
                ('description', models.TextField(blank=True, max_length=1126, null=True, verbose_name='Opis kategorii')),
            ],
            options={
                'verbose_name': 'Typ gry',
                'verbose_name_plural': '_Typy Gry',
            },
        ),
        migrations.CreateModel(
            name='MechanicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa mechaniki')),
                ('description', models.TextField(blank=True, max_length=1126, null=True, verbose_name='Opis mechaniki')),
            ],
            options={
                'verbose_name': 'Mechanika',
                'verbose_name_plural': '_Mechaniki gier',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Nazwa gry')),
                ('description', models.TextField(blank=True, verbose_name='Opis gry')),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images', verbose_name='Zdjęcie gry')),
                ('min_player', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minimalna liczba graczy')),
                ('max_player', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maksymalna liczb graczy')),
                ('min_play_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimalny czas gry(minuty)')),
                ('game_type', models.ManyToManyField(blank=True, to='main.GameType', verbose_name='Rodzaj gry')),
                ('mechanic_type', models.ManyToManyField(blank=True, to='main.MechanicType', verbose_name='Rodzaj gry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Users')),
            ],
        ),
    ]
