# Generated by Django 3.0.3 on 2020-02-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_choose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='choose',
        ),
        migrations.RemoveField(
            model_name='person',
            name='preferences',
        ),
    ]
