# Generated by Django 3.0.3 on 2020-02-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200223_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='choose',
            field=models.BooleanField(default=False, verbose_name='Wybierz'),
        ),
        migrations.AddField(
            model_name='person',
            name='preferences',
            field=models.ManyToManyField(to='main.Preferences', verbose_name='Preferencja gracza'),
        ),
    ]
