# Generated by Django 3.0.3 on 2020-02-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200223_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='choose',
        ),
        migrations.RemoveField(
            model_name='person',
            name='preferences',
        ),
    ]
